FROM alpine
MAINTAINER Frederic Branczyk <fbranczyk@gmail.com>

RUN apk --update add bash nginx && \
    rm -rf /var/cache/apk/*

COPY dist /usr/share/nginx/html

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
